function cfgs = build_ablation_configs_loss()
% English comments only
% Fixed feature setting: 16 dims
% Fixed width setting: neuron divisor = 2
% Ablation only on loss design

baseNeurons = [160 240 320 360 480 520 600];
fixedDiv = 2;

fixedNumNeurons = round(baseNeurons / fixedDiv);
fixedNumNeurons(fixedNumNeurons < 8) = 8;

% English comment: change this line only if your current 16-feature set is different
fixedFeatureIdx = [1:11 16:20];

epsA = 1e-4;
tau  = 1e-2;

cfgs = struct( ...
    'id', {}, ...
    'name', {}, ...
    'loss_name', {}, ...
    'loss_mode', {}, ...
    'use_weight', {}, ...
    'use_norm', {}, ...
    'feature_idx', {}, ...
    'nfeatures', {}, ...
    'neuron_div', {}, ...
    'numNeurons', {}, ...
    'epsA', {}, ...
    'tau', {});

defs = { ...
    'relCplx', 1, 1, 1; ...
    'relCplx', 1, 1, 0; ...
    'relCplx', 1, 0, 1; ...
    'relCplx', 1, 0, 0; ...
    'plainL1', 2, 0, 0; ...
    'plainL2', 3, 0, 0; ...
    };

for k = 1:size(defs, 1)
    cfgs(k).id          = k; %#ok<AGROW>
    cfgs(k).loss_name   = defs{k,1}; %#ok<AGROW>
    cfgs(k).loss_mode   = defs{k,2}; %#ok<AGROW>
    cfgs(k).use_weight  = defs{k,3}; %#ok<AGROW>
    cfgs(k).use_norm    = defs{k,4}; %#ok<AGROW>

    cfgs(k).feature_idx = fixedFeatureIdx; %#ok<AGROW>
    cfgs(k).nfeatures   = numel(fixedFeatureIdx); %#ok<AGROW>
    cfgs(k).neuron_div  = fixedDiv; %#ok<AGROW>
    cfgs(k).numNeurons  = fixedNumNeurons; %#ok<AGROW>
    cfgs(k).epsA        = epsA; %#ok<AGROW>
    cfgs(k).tau         = tau; %#ok<AGROW>

    if cfgs(k).loss_mode == 1
        cfgs(k).name = sprintf('LOSS%02d__%s__W%d__N%d', ...
            k, cfgs(k).loss_name, cfgs(k).use_weight, cfgs(k).use_norm); %#ok<AGROW>
    else
        cfgs(k).name = sprintf('LOSS%02d__%s', ...
            k, cfgs(k).loss_name); %#ok<AGROW>
    end
end
end